version: '3.9'

services:

  server-backend:
    build:
      context: ./server
      dockerfile: Dockerfile

    image: server_image
    container_name: server-container
    #command: ./node_modules/.bin/nodemon server.js

    ports:
      - "3000:3000"

    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin

      # ME_CONFIG_MONGODB_AUTH_USERNAME: root
      # ME_CONFIG_MONGODB_AUTH_PASSWORD: example

      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      #ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"


  server:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client_image
    container_name: client-container

    #command: npm start

    depends_on:
      - server-backend
    ports:
      - "8080:3001"