version: '3.9'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin

      # ME_CONFIG_MONGODB_AUTH_USERNAME: root
      # ME_CONFIG_MONGODB_AUTH_PASSWORD: example

      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      #ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

  server:
    build:
    ports:
      - 3000:8080
      - 3001:3001
